# Generated by Django 2.1.4 on 2019-03-07 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('first_score', models.IntegerField(default=0, verbose_name='First Score')),
                ('second_score', models.IntegerField(default=0, verbose_name='Second Score')),
                ('third_score', models.IntegerField(default=0, verbose_name='Third Score')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on-moderation', 'On moderation'), ('reviewed', 'Reviewed')], default='on-moderation', max_length=100)),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('first_image', models.ImageField(upload_to='', verbose_name='first image')),
                ('second_image', models.ImageField(upload_to='', verbose_name='second image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='review',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='works.Work'),
        ),
    ]
