# Generated by Django 2.1.4 on 2019-03-12 06:39
from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_test_user(apps, schema_editor):
    User = apps.get_model('a12n.User')
    User.objects.create(
        email='moderator@stepik.stepik',
        password=make_password('test123'),
        username='moderator',
        is_staff=True,
        is_superuser=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('a12n', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_user),
    ]
